name: "Tagged Release"

on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  linux-release-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev libxtst-dev
        sudo apt-get install libadwaita-1-dev libgtk-4-dev
    - name: Release Build
      run: cargo build --release
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/lan-mouse

  windows-release-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Release Build (headless, no GTK)
      run: cargo build --release --no-default-features
    - name: Package
      run: |
        mkdir lan-mouse-windows
        Copy-Item -Path "target\release\lan-mouse.exe" -Destination "lan-mouse-windows"
        Compress-Archive -Path "lan-mouse-windows\*" -DestinationPath lan-mouse-windows.zip
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: lan-mouse-windows.zip

  macos-release-build:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: brew install pkgconf gtk4 libadwaita
    - name: Release Build
      run: |
        cargo build --release
        cp target/release/lan-mouse lan-mouse-macos-intel
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: lan-mouse-macos-intel

  macos-aarch64-release-build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: brew install pkgconf gtk4 libadwaita
    - name: Release Build
      run: |
        cargo build --release
        cp target/release/lan-mouse lan-mouse-macos-aarch64
    - name: Upload to release
      uses: softprops/action-gh-release@v2
      with:
        files: lan-mouse-macos-aarch64
